name:                mt5haskell
version:             0.1.0.0
github:              "github.com/schnecki/mt5haskell"
license:             BSD-3-Clause
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schnecki@gmail.com"
copyright:           "2025 Manuel Schneckenreither"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mt5haskell#readme>

dependencies:
- base >= 4.7 && < 5
- data-default
- directory
- deepseq
- text
- process
- regex-compat
- easy-logger
- bytestring
- python-pickle
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mt5haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mt5haskell

tests:
  mt5haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mt5haskell
